version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: eth_log_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ethlog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
